version: '3.3'

services:
   web-service:
     depends_on:
       - model-service
     image: mdcgl96/djl-serving-projekt2:latest
     ports:
       - "80:8082"
     restart: always

   model-service:
     image: mdcgl96/djl-model-serving-projekt2:latest
     restart: always
